got multiple files, spaces in filenames, and arguments to open working

diff --git a/macopen b/macopen
--- a/macopen
+++ b/macopen
@@ -1,14 +1,32 @@
 #!/bin/bash
 
 usage() {
-  echo "Usage: macopen [-u <eduser>] [-h <host>] [-U <fsuser>] <filename> [<filename2>...<filenameN>] [-A openArguments]"
+  echo "Usage: macopen [-u <eduser>] [-h <host>] [-U <fsuser>] [-H <fshost>] [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b <bundle identifier>] [-a <application>] <filename> [<filename2>...<filenameN>] [--args arguments]"
   echo "Help: Connects via SSH to the specified Mac, mounts this host's filesystem via SSHFS,"
   echo "      and opens the specified file(s) using the 'open' command."
   echo "Options:"
-  echo "      -u Connects to the Mac as the specified user"
-  echo "      -h Connects to the specified host"
-  echo "      -U Mounts this host's filesystem as the specified user"
-  echo "      -H Overrides the host name for the connection to this host's filesystem"
+  echo "      -u eduser"
+  echo "          Connects to the Mac as the specified user\n"
+  echo "      -h host"
+  echo "          Connects to the specified host\n"
+  echo "      -U fsuser"
+  echo "          Mounts this host's filesystem as the specified user\n"
+  echo "      -H fshost"
+  echo "          Overrides the host name for the connection to this host's filesystem\n"
+  echo "      -a application [passed through to 'open' command]"
+  echo "          Specifies the application to use for opening the file\n"
+  echo "      -b bundle_indentifier [passed through to 'open' command]"
+  echo "          Specifies the bundle identifier for the application to use when opening the file\n"
+  echo "      -e  [passed through to 'open' command] Causes the file to be opened with /Applications/TextEdit\n"
+  echo "      -t  [passed through to 'open' command] Causes the file to be opened with the default text editor, as determined via LaunchServices\n"
+  #echo "      -f  [passed through to 'open' command] Reads input from standard input and opens the results in the default text editor.  End input by sending EOF character (type Control-D).  Also useful for piping output to open and having it open in the default text editor.\n"
+  echo "      -F  [passed through to 'open' command] Opens the application 'fresh,' that is, without restoring windows. Saved persistent state is lost, except for Untitled documents.\n"
+  echo "      -W  [passed through to 'open' command] Causes open to wait until the applications it opens (or that were already open) have exited.  Use with the -n flag to allow open to function as an appropriate app for the \$EDITOR environment variable.\n"
+  echo "      -R  [passed through to 'open' command] Reveals the file(s) in the Finder instead of opening them.\n"
+  echo "      -n  [passed through to 'open' command] Open a new instance of the application(s) even if one is already running.\n"
+  echo "      -g  [passed through to 'open' command] Do not bring the application to the foreground.\n"
+	echo "      -j  [passed through to 'open' command] Launches the app hidden.\n"
+	echo "      -z  [passed as '-h' to 'open' command] Searches header file locations for headers matching the given filenames, and opens them.\n"
 }
 
 # Set the ED_USER variable that determines the user with which we'll log into
@@ -49,61 +67,76 @@ FS_USER="$USER"
 
 # parse the command-line options using bash's built-in getopts
 
-while getopts ":u:h:U:H:" opt; do
-  case $opt in
-    u)
-      ED_USER="$OPTARG"
-      ;;
-    h)
-      ED_HOST="$OPTARG"
-      ;;
-    U)
-      FS_USER="$OPTARG"
-      ;;
-    H)
-      FS_HOST="$OPTARG"
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      usage
-      exit 1
-      ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      usage
-      exit 1
-      ;;
-  esac
+OPEN_ARGS=()
+
+APP_ARGS=()
+
+while getopts ":u:h:U:H:a:b:etFWRngjz" opt; do
+	case $opt in
+		u)
+			ED_USER="$OPTARG"
+			;;
+	  h)
+			ED_HOST="$OPTARG"
+			;;
+		U)
+			FS_USER="$OPTARG"
+			;;
+		H)
+			FS_HOST="$OPTARG"
+			;;
+		a|b)
+			OPEN_ARGS+=( "-$opt" "$OPTARG" )
+			;;
+		e|t|F|W|R|n|g|j)
+			OPEN_ARGS+=( "-$opt" )
+			;;
+		z)
+			OPEN_ARGS+=( "-h" )
+			;;
+		\?)
+	    echo "Invalid option: -$OPTARG" >&2
+	    usage
+	    exit 1
+			;;
+		:)
+	    echo "Option -$OPTARG requires an argument." >&2
+	    usage
+	    exit 1
+			;;
+	esac
 done
 
 shift $((OPTIND-1))
 
-echo "after getopts, OPTIND=$OPTIND and \$1=$1"
-
-OPEN_ARGS=""
-FS_PATHS=""
+FS_PATHS=()
 
 MOUNTS_DIR='$HOME/.macopen_mounts'
 MOUNT_DIR="$MOUNTS_DIR/$FS_USER@$FS_HOST"
 
-while [ -n "$1" ] && [ "$1" != "-A" ]
+while [ -n "$1" ] && [ "$1" != "--args" ]
 do
-  FILENAME=`basename $1`
+  FILENAME=$(basename "$1")
   DIRNAME=$(cd "$(dirname "$1")"; pwd)
   LOCAL_PATH=$(echo "$DIRNAME/$FILENAME" | sed 's|^/||')
-  FS_PATH="$MOUNT_DIR/$LOCAL_PATH"
-  if [ -n "$FS_PATHS" ]; then
-    FS_PATHS="$FS_PATHS \"$FS_PATH\""
-  else
-    FS_PATHS="\"$FS_PATH\""
-  fi
+	FS_PATHS+=( "$MOUNT_DIR/$LOCAL_PATH" )
   shift
 done
 
-if [ -z "$FS_PATHS" ]; then
+if [ ${#FS_PATHS[@]} -eq 0 ]; then
   echo "No filename specifed." >&2
   usage
   exit 1
+fi
+
+if [ "$1" == "--args" ]; then
+	APP_ARGS=( "--args" )
+	shift
+	while [ -n "$1" ]
+	do
+		APP_ARGS+=( "$1" )
+		shift
+	done
 fi
 
 if [ -z "$ED_HOST" ]; then
@@ -113,15 +146,21 @@ if [ -z "$ED_HOST" ]; then
   echo "  3) Specify the host on the command line via the -h option"
 fi
 
-echo "FS_PATHS=$FS_PATHS"
+printf "%s\n" "${FS_PATHS[@]}"
 
-MOUNT_AND_OPEN_SCRIPT=$(cat <<EOF
+FS_PATHS=("${FS_PATHS[@]}") 
+
+printf "%s\n" "${FS_PATHS[@]}"
+
+MOUNT_AND_OPEN_SCRIPT=$(cat <<'EOF'
+
+printf "%s\n" "${FS_PATHS[@]}"
 
 if [ ! -d "$MOUNTS_DIR" ]; then
  mkdir "$MOUNTS_DIR"
 fi
 
-if [ ! -d $MOUNT_DIR ]; then
+if [ ! -d "$MOUNT_DIR" ]; then
   mkdir "$MOUNT_DIR"
 fi
 
@@ -131,12 +170,20 @@ else
   /usr/local/bin/sshfs -o follow_symlinks,volname=$FS_HOST $FS_USER@$FS_HOST:/ "$MOUNT_DIR"
 fi
 
-echo "open $OPEN_ARGS $FS_PATHS"
+FS_PATHS_STRING=`printf "'%s' " "${FS_PATHS[@]}"`
+OPEN_ARGS_STRING=`printf "'%s' " "${OPEN_ARGS[@]}"`
+APP_ARGS_STRING=`printf "'%s' " "${APP_ARGS[@]}"`
 
-open $OPEN_ARGS $FS_PATHS
+eval "echo open $OPEN_ARGS_STRING $FS_PATHS_STRING $APP_ARGS_STRING"
+
+eval "open $OPEN_ARGS_STRING $FS_PATHS_STRING $APP_ARGS_STRING"
 
 EOF
 );
+
+FS_PATHS_STRING=`printf "\"%s\" " "${FS_PATHS[@]}"`
+OPEN_ARGS_STRING=`printf "\"%s\" " "${OPEN_ARGS[@]}"`
+APP_ARGS_STRING=`printf "\"%s\" " "${APP_ARGS[@]}"`
 
 echo "trying ssh ${ED_USER}@${ED_HOST}"
 
@@ -144,8 +191,9 @@ ssh "${ED_USER}@${ED_HOST}" <<EOF
 
 FS_HOST="$FS_HOST"
 FS_USER="$FS_USER"
-FS_PATHS="$FS_PATHS"
-OPEN_ARGS="$OPEN_ARGS"
+FS_PATHS=($FS_PATHS_STRING) 
+OPEN_ARGS=($OPEN_ARGS_STRING)
+APP_ARGS=($APP_ARGS_STRING)
 MOUNTS_DIR="$MOUNTS_DIR"
 MOUNT_DIR="$MOUNT_DIR"
 
